### ISSUE TITLE
Docs link broken

### ISSUE THREAD

**Issue by ju-sh** [libindic/payyans#12]
The link to docs in the Readme file is broken.

If more docs is available, can it be put up?

**Comment by asdofindia** [comment]
I don't know if more documentation is available. What documentation are you looking for? What're you trying to solve?

**Comment by ju-sh** [comment]
I don't have anything specific. I just happened to come across this project. 

I didn't know what what text encoded in ascii meant. I mean, using what rules or specification were they encoded in ascii in the first place so that they may be converted to unicode using this library?

The example shown in the readme is nice. But I thought I could learn more about it by clicking on the docs link.

If docs isn't available, may be that link can be removed from the readme?

**Comment by ju-sh** [comment]
Comments and docstrings are very interesting 😃

**Comment by asdofindia** [comment]
Have removed the link and added a video explaining what ASCII is.
