### ISSUE TITLE
Missing maps

### ISSUE THREAD

**Issue by VishnuSanal** [libindic/payyans#17]
payyans was updated to use `libindic.unicode_conversion_maps` with this [commit](https://github.com/libindic/payyans/commit/c5d838f4e1ed0e7f0dd565b229df9edef40ae1e2) which points to [**libindic/unicode-conversion-maps**](https://github.com/libindic/unicode-conversion-maps). but, this repo doesn't contain all the maps that were previously supported by payyans. for eg: `ambili` which is used in the example from README.

**Comment by asdofindia** [comment]
The documentation needs to be updated as the map is now named ML-TTAmbili

We can probably also list all the maps available
