### ISSUE TITLE
Unicode2ASCII doesn't correctly place pre-base characters before the base

### ISSUE THREAD

**Issue by VishnuSanal** [libindic/payyans#21]
```
from libindic.payyans import Payyans

instance = Payyans()

print(instance.Unicode2ASCII(u"കേരളം", "ambili"))  # Itcfw

print(instance.ASCII2Unicode("Itcfw", "ambili"))  # കരേളം
```

**Comment by asdofindia** [comment]
It is unicode2ASCII that's at fault. It should be `tIcfw`. Pre-base post-base thing is not working correctly. We should implement the same three-pass logic in reverse for ASCII.

**Comment by mujeebcpy** [comment]
[#22](https://github.com/libindic/payyans/pull/22) fixed this
