### ISSUE TITLE
Better ways to handle maps

### ISSUE THREAD

**Issue by pathumego** [libindic/payyans#6]
I have a few suggestions. 
- [ ] Include a metadata field for the data currently included in the comments section. This way that data will be preserved in conversion to other formats (ie https://github.com/indicjs/map-converter) The metadata files could be `Name`,`Description`,`Copyright`,`License`

- [ ] Host maps in a different git repo and integrate as a gitsubmodule. So other projects can directly pull data from that central repo.

**Comment by asdofindia** [comment]
https://github.com/libindic/unicode-conversion-maps will be the common repo for all maps. We use github actions there to generate SDKs for all languages.
